Refactor: Make event types control the lifecycle of capture and playback #36
Leafwing-Studios/leafwing_input_playback pull request #39
Opened 2024-11-17 02:56 UTC by snendev

2024-11-17 02:57 UTC, snendev commented
Whoops! Somehow hit a button on my keyboard that submitted this much before I intended to. Will update the body shortly.

2024-11-17 03:18 UTC, snendev commented
don't know why my setup hates this repo so much. apologies for the noise. seems like it's all set now :+1:

2024-11-18 05:43 UTC, snendev commented
hey @alice-i-cecile, that's completely fine -- in that case I would suggest closing this and preferring #36 -- that PR works just fine for an event-based approach. after the conversation in #36, I wanted to post what work I had on-going in case it was useful for anyone.

the reasons I thought to try this observer-based approach were:

- I don't see sending events or triggering observers as more- or less-simple than one another from a user-API standpoint -- arguably the use of commands often implies one less system parameter for a user system
- the only thing the event-consuming system does is apply commands (inserting resources), so it somewhat makes sense to offer users a way to apply all those commands at once anyway (in case they want to do that themselves for some reason)
- I am not sure that a user will ever expect to read the events in other places than the one that applies commands, so it isn't particularly useful to keep the events in the Event queue that I can think of
- there is the possibility to extend this into a model where these observers _do_ spawn, update, and despawn Entities to allow more complicated storage/retrievable of input sequences if desired (which I was originally very curious to explore and might return to in a more general fashion at some point soon)

all that said, like I said, this was mostly the product of a rabbit-hole, I just thought it worth sharing for your (and hopefully @JeanMertz's) consideration

2024-11-18 05:54 UTC, JeanMertz commented
I actually had the same idea of allowing multiple recordings at the same time (e.g. targeting different windows or input devices, or only recording interactions with specific entities), at which point recording or playback could become entity based instead of globally.

I haven’t worked with observers before, but their “instant” nature seemed preferable for starting and stopping recordings at the exact time.

2024-11-18 20:13 UTC, snendev commented
I'm sufficiently satisfied with the implementation for the time being, and I don't intend to add anything else unless asked to. I'm not sure that implies "ready to be merged" though 😅 -- I'd feel more comfortable saying so after a reviewer does.

2024-11-19 21:27 UTC, alice-i-cecile commented on src/input_playback.rs
> +/// An Event that users can send to initiate input capture.
These docs need to explain that this is sent as an observer. Ditto elsewhere.

2024-11-19 21:27 UTC, alice-i-cecile commented on src/input_playback.rs
> +pub enum InputPlaybackSource {
I love this :D

2024-11-19 21:28 UTC, alice-i-cecile requested changes
Okay, I'm happy with the approach and the code quality is good. It needs a bit of care with docs: an example would be helpful, and we definitely need to explain that these are triggered as observers.

The other thing to do is to add a note in RELEASES.md :)

2024-11-21 20:42 UTC, snendev commented
Thanks a bunch for taking the time @alice-i-cecile! I'll be able to finish this up after the weekend.

2024-11-30 02:51 UTC, snendev commented
Okay, back again. I finished up the examples -- turns out I hadn't completely wired up `PlaybackWindow`, so that's my bad.

After the last updates, all the examples should be fixed up to run as intended (I think). I've included some doc updates and the additional wiring to actually override serialized window entities when provided. (I'd have broken up the commits but I had a little trouble with the environment while traveling -- my apologies if I end up having to throw up a few commits after this one lol.)

To be honest though, the code in the `CursorMoved` portion of the `send_playback_events` function makes me think the approach I'm trying -- expecting users to manually opt-in to the window override, and then only handling that override for keyboard, mouse, and mousewheel events --  is a little smelly. Let me know if you have any thoughts about it.

2024-11-30 02:53 UTC, snendev commented
Also, congrats on 0.15! I'll follow this up with an update for that when I'm home.

2024-12-02 15:12 UTC, alice-i-cecile approved these changes

2024-12-02 15:12 UTC, merged

2024-12-02 15:12 UTC, alice-i-cecile commented
Great! I'll ship this out with the new Bevy version bump this week.