Upgrade Bevy to 0.15
Leafwing-Studios/leafwing_input_playback pull request #40
Opened 2024-12-03 06:49 UTC by snendev

# Issue

This upgrades Bevy to 0.15.

# Changes

- Included the required `bevy_window` feature in dependencies
- Renamed `App::observe` to `App::add_observer`
- Renamed `Condition(?)::and_then` to `::and`
- Added `repeat` field to keyboard inputs
- `World::flush_commnads` is now private, replaced with `World::flush`
- Updated `gamepad` example to accommodate refactors around (1) gamepads (now entities instead of tracked by resources) and (2) Text. This comprises the bulk of the meaningful changes.

2024-12-03 15:55 UTC, alice-i-cecile commented
Fantastic. Thanks for all your help here; I've sent you an invite for maintainer privileges on Github for this crate. I'm not actively using it, so it's nice to share the load and get real user feedback.

2024-12-03 15:56 UTC, alice-i-cecile requested changes
Changes look good, but this needs release notes. Can you bump the crate version number in this PR too so we can release right after this is merged?

2024-12-03 20:52 UTC, snendev commented
🤦🏻 my bad, I've forgotten release notes every time. can do!

2024-12-04 18:26 UTC, alice-i-cecile approved these changes

2024-12-04 18:26 UTC, merged